### ISSUE TITLE
Idea: bot that validates that the submitter is a maintainer of a given repository

### ISSUE THREAD

**Issue by kubukoz** [scala-steward-org/repos#789]
This would probably be implemented as a GitHub Action. The GH API probably offers that kind of data, so we could speed up the review process by validating whether the submitting user has write access to all the repos being added to/removed from the list.

**Comment by exoego** [comment]
I am already working on this!

**Comment by exoego** [comment]
https://github.com/exoego/repos/pull/1#issuecomment-925018316

This is a PoC.

**Comment by exoego** [comment]
Hmm, it looks like it is difficult to check an actor is a collaborator of a repo via GH API.

[This api](https://docs.github.com/en/rest/reference/repos#get-repository-permissions-for-a-user) can be used only if api caller (github action for this context) have push access to the target repo.
Otherwise, the below error occurs.

```json
{ 
"message": "Must have push access to view repository collaborators.",
"documentation_url": "https://docs.github.com/rest/reference/repos#check-if-a-user-is-a-repository-collaborator" 
}
```

I will try to find a workaround.

**Comment by exoego** [comment]
My workaround
- A bot checks if an actor is a repo owner or an organization administrator
- Otherwise, manual verification.
